---
# tasks file for aws.vpc_facts
- name: Get subnet facts.
  ec2_vpc_subnet_facts:
    region: "{{ vpc.region }}"
    filters: "{{ filters }}"
  register: subnet_facts

- name: Get VPC ID fact.
  set_fact:
    vpc_id_fact: "{{ subnet_facts.subnets|selectattr('tags.Environment', 'equalto', vpc.resource_tags.Environment)|map(attribute='vpc_id')|list|first }}"
