---
# wordpress.yml
#
# This playbook deploys an AWS infrastructure and two instances; a wordpress
#   instance and a mysql instance.  It deploys all infrastucture from the ground up.
#   All that is needed is an AWS account, an IAM access/secret key setup, and an
#   uploaded SSH key (defaults to defaultkey).
#
# Both instances use public IP addresses, so no bastion host is needed.
#
#####
# Initial AWS deployment
#####
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/{{ env }}_aws/aws.yml
    - vars/{{ env }}_aws/vault.yml
    - vars/wordpress.yml

  roles:
    - role: aws.vpc
    - role: aws.vpc_facts
      filters:
        "tag:Environment" "{{ env }}"
    - role: aws.routes
    - role: aws.securitygroups
    - role: aws.iam
    - role: aws.ec2
    - role: aws.ec2_facts
      filters:
        "tag:Environment": "{{ env }}"
        instance-state-name: running
    - role: localhost.aws_ssh_keys
    - role: ansible.groups_init


#####
# Initial raw configuration
#####
- hosts: wordpress1_public:mysql1_public
  become: yes
  gather_facts: no
  user: ubuntu

  roles:
    - role: ubuntu.raw_install_python

#####
# Configure shared services on Wordpress and MySQL
#####
- hosts: wordpress1_public:mysql1_public
  become: yes
  remote_user: ubuntu
  gather_facts: yes

  vars_files:
    - vars/aws_infrastructure.yml

  roles:
    - role: instance.ssh_aws_public_key
    - role: instance.docker_install
    - role: instance.automated_updates
      update_date: 'Tue, 07:00'
    - role: instance.hosts
    - role: localhost.aws_ssh_keys
    - role: ansible.groups_init
